### PR TITLE
Dont duplicate `import Vue`

### LINKED ISSUE #128: Server still crash on 0.6.1 - throw new Error("start < 0");
Still having issue with server, last VSCode version on ArchLinux updated with node v7.8.0
```
/home/xxxxxx/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:10566
            throw new Error("start < 0");
            ^

Error: start < 0
    at createTextSpan (/home/xxxxxx/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:10566:19)
    at Object.createTextSpanFromBounds (/home/xxxxxx/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:10575:16)
    at getErrorSpanForNode (/home/xxxxxx/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:7075:19)
    at createDiagnosticForNodeInSourceFile (/home/xxxxxx/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:6999:20)
    at Object.createDiagnosticForNode (/home/xxxxxx/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:6995:16)
    at /home/xxxxxx/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:21582:58
    at Object.forEach (/home/xxxxxx/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:1423:30)
    at declareSymbol (/home/xxxxxx/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:21581:28)
    at declareModuleMember (/home/xxxxxx/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:21600:28)
    at declareSourceFileMember (/home/xxxxxx/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:22646:19)
    at declareSymbolAndAddToSymbolTableWorker (/home/xxxxxx/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:22596:28)
[Error - 7:43:37 PM] Connection to server got closed. Server will not be restarted.

```

### PR DESCRIPTION
**Pull request by sandersn**
Don't import `import Vue from 'vue'` if user already imports Vue themselves (perhaps even from somewhere else)

Fixes #128

### CODE REVIEW

File: server/src/modes/typescriptMode.ts [hunk 1]
```diff
@@ -52,14 +52,17 @@ function modifyVueSource(sourceFile: ts.SourceFile): void {
...
   if (exportDefaultObject) {
-    // 1. add `import Vue from './vue'
-    //    (the span of the inserted statement must be (0,0) to avoid overlapping existing statements)
-    const setZeroPos = getWrapperRangeSetter({ pos: 0, end: 0 });
-    const vueImport = setZeroPos(ts.createImportDeclaration(undefined,
-      undefined,
-      setZeroPos(ts.createImportClause(ts.createIdentifier('Vue'), undefined)),
-      setZeroPos(ts.createLiteral('vue'))));
-    sourceFile.statements.unshift(vueImport);
+    const isVueAlreadyImported = find(sourceFile.statements, st => isImportOfName(st, 'Vue'));
```
Comment (octref) [inline server/src/modes/typescriptMode.ts]: Would this be too costly? If I understand correctly this will be run on each sourceFile in the workspace.

Was planning to use a similar approach for parsing the `props` and `methods` properties for each export object.

Comment (sandersn) [inline server/src/modes/typescriptMode.ts]: It should only be .vue files, which I expect to have few top-level statements; `create/updateLanguageSourceFile` checks each file with `isVue`. 

But yes, each call to `find` iterates over each of the statements. I could instead merge the two calls into a single `for .. of` loop in `modifyVueSource`. That would still iterate once though.

Comment (sandersn) [inline server/src/modes/typescriptMode.ts]: Never mind, it would still need an initial pass to find out if there is a `import Vue ...` statement before we could know whether to insert our own `import Vue from 'vue'`.

**Comment by octref** [comment]
Thanks!
